### ISSUE TITLE
Container for AMD

### ISSUE THREAD

**Issue by erich3000** [thaibault/containerbase#3]
Hi,

the latest container is only build for ARM Arch, is is possible to build it for both ARM and AMD architectures ?

We still not have our fork running :-(

thanks and greetings from the JR Gang

![Bildschirmfoto 2023-10-02 um 08 16 12](https://github.com/thaibault/containerbase/assets/6512827/0ada8db3-d129-44c6-9701-0a034c86ed38)

**Comment by thaibault** [comment]
yess, i disabled amd caused by an github harddrive space overflow and i
needed arm quickly. AMD should be available soon.

Jens Ihrig ***@***.***> schrieb am Mo., 2. Okt. 2023, 08:17:

**Comment by thaibault** [comment]
The latest build v1.0.181 now supports multiple architectures again.
The issue occurs because of an unstable base image. Now the build is made from scratch and has no dependencies anymore and should be more stable therefore.
You can also reference the version tag (v1.0.181 e.g.) instead of "latest" to may build more stable.
